language: php
php:
  - 8.2
  - nightly

before_script:
  - composer self-update
  - composer install --optimize-autoloader --prefer-dist --no-interaction --no-progress --no-suggest

script:
  - vendor/bin/robo --no-interaction code:cs --strict

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
